server:
  port: 9000

spring:
  application:
    name: Nacos-consumer-9000
  cloud:
    sentinel:
      enabled: true
      transport:
        dashboard: localhost:8080
    nacos:
      discovery:
        server-addr: 47.106.132.130:8848

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://47.106.132.130:3306/cloud?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456


  redis:
    password: 123456
    host: 47.106.132.130
    port: 6379

management:
  endpoint:
    web:
      exposure:
        include: '*'
feign:
  sentinel:
    enabled: true

